project:
  type: website
  resources: /assets 

website:
  title: "Caiya Coggshall's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: resume.qmd
        text: Resume
      - text: All Projects  
        menu:
          - href: m_m.qmd
            text: Mechanical and Manufacturing
          - href: e_h.qmd
            text: Electrical and Hardware
          - href: s.qmd
            text: Software

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



